[5.x] Improve bash scripts

diff --git a/src/php/with-unit/rootfs/usr/local/bin/unit-conf b/src/php/with-unit/rootfs/usr/local/bin/unit-conf
--- a/src/php/with-unit/rootfs/usr/local/bin/unit-conf
+++ b/src/php/with-unit/rootfs/usr/local/bin/unit-conf
@@ -6,64 +6,66 @@
 #      - Author:  SHIN Company <shin@shin.company>
 #      - License: https://code.shin.company/php/blob/main/LICENSE
 ################################################################################
+socket="${UNIT_CONTROL_SOCKET:-/run/control.unit.sock}"
+default_config_path="config/"
+tmpfile=""
 
-config_file="$1"
+cleanup() {
+    [[ -n "$tmpfile" && -f "$tmpfile" ]] && rm -f "$tmpfile"
+}
+trap cleanup EXIT
 
-if [ -z "$config_file" ]; then
-    debug-echo -w "Usage: ${0##*/} /path/to/config.json <config/path>"
+config_file="${1:-}"
+config_path="${2:-$default_config_path}"
+
+if [[ -z "$config_file" ]]; then
+    debug-echo -w "Usage: ${0##*/} /path/to/config.json [config/path]"
     exit 1
 fi
 
-if [ ! -f "$config_file" ]; then
-    debug-echo -e "Error: Invalid config file: $config_file."
+if [[ ! -f "$config_file" ]]; then
+    debug-echo -e "Error: Invalid config file: $config_file"
     exit 1
 fi
 
-set -e
-
-shift
-config_path="$@"
-
-if [ -z "$config_path" ]; then
-    config_path="config/"
-fi
-
-envsubst() {
-    while IFS= read -r line; do
-        while [[ $line =~ (\{\{ [a-zA-Z_][a-zA-Z_0-9]* \}\}) ]]; do
-            var="${BASH_REMATCH[1]}"
-            var_name="${var:3:-3}"
-            var_value="${!var_name}"
-            line="${line//$var/$var_value}"
+envsubst_template() {
+    while IFS= read -r line || [[ -n "$line" ]]; do
+        while [[ "$line" =~ (\{\{[[:space:]]*([a-zA-Z_][a-zA-Z_0-9]*)[[:space:]]*\}\}) ]]; do
+            full="${BASH_REMATCH[1]}"
+            var="${BASH_REMATCH[2]}"
+            val="${!var:-}"
+            line="${line//$full/$val}"
         done
         echo "$line"
     done
 }
 
-if [[ $config_file == *".json" ]]; then
-    output="/tmp/${config_file##*/}"
-    echo "$(cat "$config_file" | envsubst)" >$output
-    config_file="$output"
+if [[ "$config_file" == *.json ]]; then
+    tmpfile="$(mktemp /tmp/unitconf.XXXXXX.json)"
+    envsubst_template < "$config_file" > "$tmpfile"
+    config_file="$tmpfile"
 fi
 
-RET=$(
-    if is-debug; then cat $config_file; set -x; fi;
-    curl --retry 3 --retry-delay 5 -sSL -w '%{http_code}' \
-        -X PUT --data-binary @$config_file \
-        --unix-socket ${UNIT_CONTROL_SOCKET:-/run/control.unit.sock} \
-        "http://localhost/$config_path"
-)
-STATUS=$(echo $RET | tail -c 4)
+debug-echo "Sending configuration to Unit at path: /$config_path"
 
-if [ ! -z "$output" ]; then
-    rm -f "$output"
+if is-debug; then
+    echo "---- Config Payload ----"
+    cat "$config_file"
+    echo "------------------------"
 fi
 
-debug-echo "$RET."
+http_body="$(mktemp)"
+http_code=$(download -X PUT --data-binary @"$config_file" \
+    --unix-socket "$socket" \
+    -w "%{http_code}" -o "$http_body" \
+    "http://localhost/$config_path")
 
-if [ "$STATUS" != "200" ]; then
-    debug-echo -e "Error: HTTP response status code is '$STATUS'."
+[[ "$(is-debug)" == "1" ]] && cat "$http_body"
+
+if [[ "$http_code" != "200" ]]; then
+    debug-echo -e "Error: HTTP response status code is '$http_code'."
+    cat "$http_body"
     exit 1
+else
+    debug-echo -s "OK: HTTP response status code is '$http_code'."
 fi
-
-debug-echo -s "OK: HTTP response status code is '$STATUS'."
