refactor: some minor enhancements (#292)

diff --git a/src/php/common/rootfs/usr/local/sbin/msmtp-wrapper b/src/php/common/rootfs/usr/local/sbin/msmtp-wrapper
--- a/src/php/common/rootfs/usr/local/sbin/msmtp-wrapper
+++ b/src/php/common/rootfs/usr/local/sbin/msmtp-wrapper
@@ -1,87 +1,75 @@
 #!/usr/bin/env sh
 ##
 # Source: https://gist.github.com/onnimonni/e7f2a5199d6dc719ffd32dc4d6ac1902
-# This is custom wrapper for msmtp which acts like good old sendmail
-# - It is used for php and cron
-# - This is easier to configure for external mail server than sendmail
-# - sendmail is just the default binary which other services will use
-# - It needs following env: SMTP_HOST, SMTP_PASSWORD, SMTP_PORT, SMTP_AUTH, SMTP_USER
+# This is a custom wrapper for msmtp to behave like sendmail.
+# It supports PHP and cron, and configures external SMTP via ENV vars:
+# SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, SMTP_AUTH, SMTP_FROM, SMTP_LOG, SMTP_TLS
 ##
 
-# This script gives itself as a parameter for msmtp
-# to print out the password for --passwordeval option
-# Check if msmtp called this script
+# if msmtp calls this wrapper with --passwordeval, return password
 if [ -n "$SMTP_PASSWORD" ]; then
-    PARENT_COMMANDS="$(ps -o comm= $PPID)"
-    if [[ $PARENT_COMMANDS =~ .*msmtp.* ]]; then
-        echo $SMTP_PASSWORD
-        exit 0
-    fi
+    parent_command="$(ps -o comm= "$PPID" 2>/dev/null)"
+    case "$parent_command" in
+        *msmtp*)
+            printf '%s\n' "$SMTP_PASSWORD"
+            exit 0
+            ;;
+    esac
 fi
 
-# Deduce all used msmtp options from system ENVs
-declare -a options
+# start building msmtp options
+options=""
 
-# Always extract recipients from message headers.
-if ! [[ $* == *-t* ]]; then
-    options+=('-t')
-fi
+# add -t if not already present
+echo "$@" | grep -q -- '-t' || options="$options -t"
 
-# If user didn't provide from address with -f
-# Use the SMTP_FROM variable or after that fallback for the --read-envelope-from
-if ! [[ $* == *-f* ]]; then
+# set envelope from
+echo "$@" | grep -q -- '-f' || {
     if [ -n "$SMTP_FROM" ]; then
-        options+=("--from=$SMTP_FROM")
+        options="$options --from=$SMTP_FROM"
     else
-        options+=('--read-envelope-from')
+        options="$options --read-envelope-from"
     fi
-fi
+}
 
-# Use system tls chain
+# TLS trust file (system default)
 if [ -f /etc/ssl/certs/ca-certificates.crt ]; then
-    options+=("--tls-trust-file=/etc/ssl/certs/ca-certificates.crt")
+    options="$options --tls-trust-file=/etc/ssl/certs/ca-certificates.crt"
 fi
 
+# SMTP host is mandatory
 if [ -n "$SMTP_HOST" ]; then
-    options+=("--host=$SMTP_HOST")
+    options="$options --host=$SMTP_HOST"
 else
-    echo "[mail error] SMTP_HOST is not defined, mail can't be sent"
+    echo "[mail error] SMTP_HOST is not defined, mail can't be sent" >&2
     exit 1
 fi
 
-# Log all mail requests
+# logging
 if [ -n "$SMTP_LOG" ]; then
-    options+=("--logfile=$SMTP_LOG")
+    options="$options --logfile=$SMTP_LOG"
 elif [ -f /var/log/mail.log ]; then
-    options+=("--logfile=/var/log/mail.log")
+    options="$options --logfile=/var/log/mail.log"
 fi
 
-# Default port for smtp is 25 and it will work even without this option
-if [ -n "$SMTP_PORT" ]; then
-    options+=("--port=$SMTP_PORT")
-fi
+# optional settings
+[ -n "$SMTP_PORT" ] && options="$options --port=$SMTP_PORT"
+[ -n "$SMTP_USER" ] && options="$options --user=$SMTP_USER"
 
-# Setup credentials
-if [ -n "$SMTP_USER" ]; then
-    options+=("--user=$SMTP_USER")
-fi
-
-# msmtp doesn't provide password option because usually it's unsafe
-# Use recursive hack for passwordeval
+# passwordeval requires this script to output password when called by msmtp
 if [ -n "$SMTP_PASSWORD" ]; then
-    SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
-    options+=("--passwordeval=$SCRIPT_PATH")
+    script_path="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
+    options="$options --passwordeval=$script_path"
 fi
 
+# auth toggle
 if [ -n "$SMTP_AUTH" ]; then
-    options+=("--auth=$SMTP_AUTH")
+    options="$options --auth=$SMTP_AUTH"
 elif [ -n "$SMTP_USER" ] || [ -n "$SMTP_PASSWORD" ]; then
-    options+=("--auth=on")
+    options="$options --auth=on"
 fi
 
-if [ -n "$SMTP_TLS" ]; then
-    options+=("--tls=$SMTP_TLS")
-fi
+[ -n "$SMTP_TLS" ] && options="$options --tls=$SMTP_TLS"
 
-# Add our options and command line options for msmtp
-msmtp ${options[@]} "$@"
+# finally, invoke msmtp with built options
+exec msmtp $options "$@"
diff --git a/src/php/with-apache/rootfs/usr/local/sbin/a2enmod b/src/php/with-apache/rootfs/usr/local/sbin/a2enmod
--- a/src/php/with-apache/rootfs/usr/local/sbin/a2enmod
+++ b/src/php/with-apache/rootfs/usr/local/sbin/a2enmod
@@ -7,10 +7,15 @@
 #      - License: https://code.shin.company/php/blob/main/LICENSE
 ################################################################################
 
-while [[ $# -gt 0 ]]; do
-    MODULE="$1"
-    PATTERN="/^#LoadModule ${MODULE}_module/s/^#//g"
+while [ "$#" -gt 0 ]; do
+    module="$1"
+    pattern="/^#LoadModule ${module}_module/s/^#//g"
     shift
-    debug-echo -i "Enable Apache module $MODULE."
-    sed -i "$PATTERN" /etc/apache2/*.conf &>/dev/null
+
+    debug-echo -i "Enable apache module: $module"
+
+    # enable the module in all relevant conf files
+    if ! sed -i "$pattern" /etc/apache2/*.conf 2>/dev/null; then
+        debug-echo -e "Failed to enable module: $module"
+    fi
 done
diff --git a/src/php/with-apache/rootfs/usr/local/sbin/apache-mpm b/src/php/with-apache/rootfs/usr/local/sbin/apache-mpm
--- a/src/php/with-apache/rootfs/usr/local/sbin/apache-mpm
+++ b/src/php/with-apache/rootfs/usr/local/sbin/apache-mpm
@@ -8,26 +8,49 @@
 ################################################################################
 
 config="${1:-/etc/apache2/conf-enabled/mpm_tuning.conf}"
+profile="${2:-balanced}"
 
-# Gather system information
 cpu_cores=$(grep -c ^processor /proc/cpuinfo)
 ram_mb=$(free -m | awk '/^Mem:/{print $2}')
 
-# Determine appropriate MPM module
-if [ "$(apache2 -M | grep mpm_prefork)"]; then
+if ! command -v apache2 >/dev/null 2>&1; then
+    echo "Error: apache2 command not found" >&2
+    exit 1
+fi
+
+if apache2 -M 2>/dev/null | grep -q mpm_prefork; then
     mpm_module='prefork'
 else
     mpm_module='event'
 fi
 
-# Set MPM-specific directives based on system specs and best practices
-if [[ $mpm_module == "prefork" ]]; then
-    start_servers=$((cpu_cores * 5))
-    min_spare_servers=$((cpu_cores * 2))
-    max_spare_servers=$((cpu_cores * 10))
-    max_clients=$((ram_mb / 10))
+# === hệ số điều chỉnh theo profile ===
+case "$profile" in
+  low)
+    factor_start=1
+    factor_spare=1
+    factor_clients=0.5
+    ;;
+  high)
+    factor_start=5
+    factor_spare=4
+    factor_clients=2
+    ;;
+  balanced|*)
+    factor_start=2
+    factor_spare=2
+    factor_clients=1
+    ;;
+esac
+
+if [ "$mpm_module" = "prefork" ]; then
+    start_servers=$((cpu_cores * factor_start))
+    min_spare_servers=$((cpu_cores * factor_spare))
+    max_spare_servers=$((cpu_cores * factor_spare * 2))
+    max_clients=$(awk "BEGIN {printf \"%d\", $ram_mb / 10 * $factor_clients}")
     max_requests_per_child=1000
-    cat <<EOF >$config
+
+    cat <<EOF > "$config"
 <IfModule mpm_${mpm_module}_module>
     ServerLimit 20000
     StartServers $start_servers
@@ -37,13 +60,15 @@ if [[ $mpm_module == "prefork" ]]; then
     MaxConnectionsPerChild $max_requests_per_child
 </IfModule>
 EOF
+
 else
-    start_servers=$((cpu_cores * 2))
-    min_spare_threads=$((cpu_cores * 10))
-    max_spare_threads=$((cpu_cores * 20))
+    start_servers=$((cpu_cores * factor_start))
+    min_spare_threads=$((cpu_cores * factor_spare * 5))
+    max_spare_threads=$((cpu_cores * factor_spare * 10))
     threads_per_child=25
-    max_clients=$((ram_mb / 10 / threads_per_child * threads_per_child))
-    cat <<EOF >$config
+    max_clients=$(awk "BEGIN {printf \"%d\", $ram_mb / 10 * $factor_clients / $threads_per_child * $threads_per_child}")
+
+    cat <<EOF > "$config"
 <IfModule mpm_${mpm_module}_module>
     ServerLimit 20000
     StartServers $start_servers
